version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/tokoplay

  database:
    image: mongo:latest
    ports:
      - "27017:27017"